### ISSUE TITLE
"Dockable Container Layout" resource type is available in all "new resource" dropdown menus

### ISSUE THREAD

**Issue by MaxKablaam** [gilzoide/godot-dockable-container#2]
Fantastic plugin! Not urgent bug at all.

Now that I've added dockable containers to my project, every single menu where I can select a resource, "dockable container layouts" appears as one of the options, even when it would clearly break the object.

Here it is as an option for MeshInstance:
![godot windows tools 64glTFImportBuild_Us9HVLfD2O](https://user-images.githubusercontent.com/55173884/121096662-a329b580-c7c0-11eb-8fd2-2f9b9ed0d700.png)

I don't think this needs a workaround or anything, it just looks like it may be a simple fix, so I brought it to your attention.
Thank you for the great tool!

**Comment by gilzoide** [comment]
Yeah, I've seen this before. Seems any custom type that inherits Resource just appears in every dropdown menu that accepts one... =/

In this case the custom inspector lets one edit the layout without ever needing to think about resources, I'll just remove the custom type.
Thank you very much for bringing this up! Glad you find it useful ^^
