### ISSUE TITLE
support for Godot 4.2.2

### ISSUE THREAD

**Issue by cnrdskn** [gilzoide/godot-dockable-container#30]
Great plugin but not working with Godot 4.2.2

**Comment by Yanxiyimengya** [comment]
I didn't have any problems...

**Comment by gilzoide** [comment]
Hey @cnrdskn, thanks for the report.
What does "not working" mean? The editor plugin for editing DockableContainer layouts? The DockableContainer per se when running the game/app? Are there any error messages in the Output tab? Please add more info to the issue, or there is little we can do to help.

**Comment by Yanxiyimengya** [comment]
> Hey @cnrdskn, thanks for the report. What does "not working" mean? The editor plugin for editing DockableContainer layouts? The DockableContainer per se when running the game/app? Are there any error messages in the Output tab? Please add more info to the issue, or there is little we can do to help.
Hello, in the process of using, I encountered some minor problems, when pressing the CTRL key to jump the definition of the code, the console at the bottom of the window will still output an error, but it does not affect the function of the component
`Parent node is busy setting up children, `move_child()` failed. Consider using `move_child.call_deferred(child, index)` instead (or `popup.call_deferred()` if this is from a popup).`

**Comment by cnrdskn** [comment]
> Hey @cnrdskn, thanks for the report. What does "not working" mean? The editor plugin for editing DockableContainer layouts? The DockableContainer per se when running the game/app? Are there any error messages in the Output tab? Please add more info to the issue, or there is little we can do to help.

I am truly sorry. It's my fault. I tried a different Linux kernel before and realized that not only the plugin, but also Godot, Blender, Pamac, and others were affected. After putting the system back together, I reinstalled the all softwares back, and it is now working without any problems. I have no clue what caused the previous issue; my guess is it was my kernel adventure. Everything is as it should be now. It's a great plugin, and I can't wait to use it in the project I'm working on. I will add its name and GitHub link to the project's credits. Thanks a lot and again sorry for confusion.

**Comment by Yanxiyimengya** [comment]
> Hey @cnrdskn, thanks for the report. What does "not working" mean? The editor plugin for editing DockableContainer layouts? The DockableContainer per se when running the game/app? Are there any error messages in the Output tab? Please add more info to the issue, or there is little we can do to help.

Hello, in the process of using, I encountered some minor problems, when pressing the CTRL key to jump the definition of the code, the console at the bottom of the window will still output an error, but it does not affect the function of the component
move_child()move_child.call_deferred(child, index)popup.call_deferred()Parent node is busy setting up children, failed. Consider usinginstead (or if this is from a popup).

**Comment by Lemonbrush** [comment]
Also, when I manage to grab the container side for resize it won't stop dragging after releasing so I have to spam mouse click to force the container stop dragging

**Comment by Lemonbrush** [comment]
**Split_handle.gd**

func _notification(what: int) -> void:
	if what == NOTIFICATION_MOUSE_ENTER:
		print("NOTIFICATION_MOUSE_ENTER")
		_mouse_hovering = true
		set_split_cursor(true)
		if bool(get_theme_constant("autohide", SPLIT_THEME_CLASS[layout_split.direction])):
			queue_redraw()
	elif what == NOTIFICATION_MOUSE_EXIT:
		return **<---------------------------------- THIS IS TEMPORARY WORKING FIX**
	elif what == NOTIFICATION_FOCUS_EXIT:
		print("NOTIFICATION_FOCUS_EXIT")
		_dragging = false

**Comment by gilzoide** [comment]
> I am truly sorry. It's my fault.

Don't worry @cnrdskn, this stuff happens. Good to know that you were able to fix your problem.

> It's a great plugin, and I can't wait to use it in the project I'm working on.

Really glad you like it ^^

**Comment by gilzoide** [comment]
Hey @Lemonbrush, thanks for the report. Could you please create a new issue regarding the handles, so we can keep things better organized?

As for @Yanxiyimengya, thank you for reporting the editor problem. I see you already created issue #31 about it, so we're already tracking it separately.

I'll be closing this issue now, as @cnrdskn problem is already fixed.
Thanks, everyone, cheers! \o/
