### ISSUE TITLE
Error correction in the editor

### ISSUE THREAD

**Issue by Yanxiyimengya** [gilzoide/godot-dockable-container#31]
Hello, I use Godot 4.2.1 and above, in the process of using it, an exception is thrown at the bottom of the editor, 
the number of which changes according to the number of child nodes, 
I locked the problem to line 128 of dockable_container.gd, modified it to

`_drag_n_drop_panel.move_to_front.call_deferred()`
After this line of code was modified, the editor was no longer making errors.

can you modify it?
Thanks!

**Comment by gilzoide** [comment]
Hey @Yanxiyimengya, thanks for the report.

It's quite possible that this call to `move_to_front` is unnecessary, since `_resort` also [fixes `_drag_n_drop_panel`'s order](https://github.com/gilzoide/godot-dockable-container/blob/ddff84aa31e466101b4a75c7ff68d3a82701e387/addons/dockable_container/dockable_container.gd#L306-L307).
We have to test it to make sure, but I think we can just remove this call instead of changing it to be called deferred.

**Comment by Yanxiyimengya** [comment]
> 嘿，谢谢你的报告。
> 
> 这个调用很可能是不必要的，因为也[修复了 的顺序](https://github.com/gilzoide/godot-dockable-container/blob/ddff84aa31e466101b4a75c7ff68d3a82701e387/addons/dockable_container/dockable_container.gd#L306-L307)。我们必须对其进行测试以确保，但我认为我们可以删除此调用，而不是将其更改为延迟调用。`move_to_front``_resort`

Thanks for seeing.
That means I can completely remove this line of code and it won't affect anything, right?
This is a handy plugin that helps me solve the problem of developing apps
Thank you for your efforts

**Comment by gilzoide** [comment]
> That means I can completely remove this line of code and it won't affect anything, right?

I really think removing the [call to `_drag_n_drop_panel.move_to_front()` in `_child_entered_tree`](https://github.com/gilzoide/godot-dockable-container/blob/ddff84aa31e466101b4a75c7ff68d3a82701e387/addons/dockable_container/dockable_container.gd#L128) will not break anything 🤔
This needs some testing to make sure nothing breaks. If you try this out, please comment here if it worked fine and nothing else broke afterwards. Also feel free to open a PR removing the call, after you confirm that it fixes the problem without creating new ones.

> This is a handy plugin that helps me solve the problem of developing apps

I really like this plugin as well, glad you found some good use to it ^^

**Comment by gilzoide** [comment]
Hey @Yanxiyimengya, I see you closed the issue.
So, did removing the line I mentioned fix the problem without breaking anything? Does it work?

**Comment by Yanxiyimengya** [comment]
> Hey @Yanxiyimengya, I see you closed the issue. So, did removing the line I mentioned fix the problem without breaking anything? Does it work?

Yes, there have been no more abnormalities after a few days of use, thank you very much
